version: '3.1'

services:

  db:
    image: postgres:13.3-alpine
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
        - ../database/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080